package invicta.app;

/**
 * Represents possible types of messages within the chatbot.
 * Used as keys to select message string to display.
 */
public enum MessageKey {
    // FILE / IO
    DIRECTORY_CREATED,
    DIRECTORY_CREATE_FAILED,
    DIRECTORY_FOUND,
    FILE_CREATED,
    FILE_FOUND,
    FILE_LOADING,
    FILE_LOADED,
    FILE_INVALID_TYPE,
    FILE_IO_ERROR,

    // HELP / GENERAL
    TYPE_HELP,
    DISPLAY_HELP,

    // INPUT / COMMAND ERRORS
    INVALID_COMMAND,
    INVALID_DATE_TIME,
    INVALID_INDEX,
    INVALID_LANGUAGE,
    INVALID_PERIOD,

    MISSING_LANGUAGE,
    MISSING_USERNAME,
    MISSING_INPUT,
    MISSING_INDEX,
    MISSING_NAME,
    MISSING_DEADLINE,
    MISSING_EVENT_START,
    MISSING_EVENT_END,
    MISSING_STRING,
    MISSING_DAY,
    MISSING_PERIOD_START,
    MISSING_PERIOD_END,

    // USAGE MESSAGES
    TODO_USAGE,
    DEADLINE_USAGE,
    EVENT_USAGE,
    MARK_USAGE,
    UNMARK_USAGE,
    DELETE_USAGE,
    FIND_USAGE,
    PERIOD_USAGE,
    DAY_USAGE,
    LIST_USAGE,
    LANGUAGE_USAGE,

    // CHATBOT RESPONSES
    PROMPT_USERNAME,
    PROMPT_COMMAND,
    PROMPT_LANGUAGE,

    HELLO,
    BYE,
    ADDED_TASK,
    DELETED_TASK,

    MARKED_DONE,
    MARKED_NOT_DONE,
    MARKED_DONE_ALREADY,
    MARKED_NOT_DONE_ALREADY,

    // TASK DISPLAY
    DISPLAY_TASK_LIST,
    DISPLAY_TASK_LIST_FIND,
    DISPLAY_TASK_LIST_PERIOD,
    DISPLAY_TASK_LIST_DAY,

    EMPTY_TASK_LIST,
    EMPTY_PERIOD,
    EMPTY_DAY,
    EMPTY_FIND
}
